In [135]:
import pandas as pd
import numpy as np

In [137]:
dir="F:/研究生课题/##小论文写作/数据挖掘论文/Python_Project/Processed_Data"

In [138]:
reside=["J1","J2","J3","J4","J5","J6","J7","Z1","Z2","Z3","Z4","Z5","Z6"]
reside=["J1"]
month=["02","03","04","05","06","07","08","09","10","11","12"]
month=["02"]

In [139]:
for res in reside:
    new_data=pd.DataFrame([])
    for m in month:
        directory=dir+"/"+res+"/"+res+"_"+m+".xlsx"
        data=pd.read_excel(directory,sheet_name=None)

In [140]:
print(data.keys())

odict_keys(['BR', 'WT', 'PM', 'BRWin'])

In [83]:
print(data.items())

odict_items([('BR',                     Time  Temperature  RH  HCHO  CO2  PM2.5
0    2017-02-01 00:01:49           16  53    33  400     13
1    2017-02-01 00:02:49           16  53    32  400     11
2    2017-02-01 00:03:50           16  53    33  400     16
3    2017-02-01 00:04:50           16  53    33  400      9
4    2017-02-01 00:05:53           16  53    33  400      8
5    2017-02-01 00:06:53           16  53    33  400     13
6    2017-02-01 00:07:53           16  53    32  400     11
7    2017-02-01 00:08:54           16  53    33  400     16
8    2017-02-01 00:09:54           16  53    33  400     10
9    2017-02-01 00:11:49           16  53    32  400     13
10   2017-02-01 00:12:50           16  53    33  400     10
11   2017-02-01 00:13:50           16  53    32  400     11
12   2017-02-01 00:14:50           16  53    33  400     13
13   2017-02-01 00:15:50           16  53    32  400     10
14   2017-02-01 00:16:50           16  53    33  400      8
15   2017-02-01 00:17:50           16  53    33  400      9
16   2017-02-01 00:18:50           16  53    32  400     10
17   2017-02-01 00:19:51           16  53    32  400     13
18   2017-02-01 00:21:50           16  53    33  400     13
19   2017-02-01 00:22:50           16  53    32  400     11
20   2017-02-01 00:23:50           16  53    32  400     12
21   2017-02-01 00:24:50           16  53    32  400     10
22   2017-02-01 00:25:50           16  53    33  400     10
23   2017-02-01 00:26:50           16  53    32  400     15
24   2017-02-01 00:27:50           16  53    33  400     11
25   2017-02-01 00:28:51           16  53    32  400     13
26   2017-02-01 00:29:51           16  53    33  400     10
27   2017-02-01 00:31:50           16  53    32  400     13
28   2017-02-01 00:32:50           16  53    33  400     14
29   2017-02-01 00:33:50           16  53    33  400     13
...                  ...          ...  ..   ...  ...    ...
8462 2017-02-28 23:27:55           15  52    30  442     18
8463 2017-02-28 23:28:55           15  52    30  441     18
8464 2017-02-28 23:29:55           15  52    30  440     17
8465 2017-02-28 23:31:54           15  52    32  439     22
8466 2017-02-28 23:32:54           15  52    30  439     18
8467 2017-02-28 23:33:54           15  52    32  440     17
8468 2017-02-28 23:34:55           15  52    30  440     23
8469 2017-02-28 23:35:55           15  52    30  439     23
8470 2017-02-28 23:36:55           15  52    30  440     19
8471 2017-02-28 23:37:55           15  52    30  440     21
8472 2017-02-28 23:38:55           15  52    30  440     20
8473 2017-02-28 23:39:55           15  52    30  440     24
8474 2017-02-28 23:41:54           15  52    30  440     18
8475 2017-02-28 23:42:54           15  52    30  439     21
8476 2017-02-28 23:43:55           15  52    30  439     23
8477 2017-02-28 23:44:55           15  52    30  439     22
8478 2017-02-28 23:45:58           15  52    30  438     22
8479 2017-02-28 23:46:58           15  52    30  438     23
8480 2017-02-28 23:47:58           15  52    30  439     19
8481 2017-02-28 23:48:58           15  52    30  439     20
8482 2017-02-28 23:49:59           15  52    30  439     18
8483 2017-02-28 23:51:54           15  52    30  439     24
8484 2017-02-28 23:52:54           15  52    30  439     22
8485 2017-02-28 23:53:55           15  52    30  438     20
8486 2017-02-28 23:54:55           15  52    30  437     21
8487 2017-02-28 23:55:55           15  52    30  437     18
8488 2017-02-28 23:56:55           15  52    30  437     24
8489 2017-02-28 23:57:55           15  52    30  437     23
8490 2017-02-28 23:58:55           15  52    32  437     22
8491 2017-02-28 23:59:56           15  52    30  437     23

[8492 rows x 6 columns]), ('WT',                    Time  Out_Temperature  Out_RH  Rain Wind_V Wind_D
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
0   2017-02-01 00:00:18              7.0    85.0   0.0    3-4     北风
..                  ...              ...     ...   ...    ...    ...
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风
369 2017-02-28 20:00:16             16.0    35.0   0.0    4-5    西南风

[8386 rows x 6 columns]), ('PM',                    Time  CO(mg/m3)  NO2(ug/m3)  SO2(ug/m3)  O3(ug/m3)  \
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
0   2017-02-01 00:00:26        0.6        15.0         9.0       77.0
..                  ...        ...         ...         ...        ...
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0
419 2017-02-28 20:00:15        0.9        21.0        10.0      105.0

     PM10(ug/m3)  PM2.5(ug/m3)   AQI
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
0           40.0          21.0  40.0
..           ...           ...   ...
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0
419         73.0          23.0  62.0

[8386 rows x 8 columns]), ('BRWin',     BRW                Time
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
..  ...                 ...
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19
0     0 2017-02-08 11:25:19

[184 rows x 2 columns])])

In [84]:
print(ik_data['BR'])

                    Time  Temperature  RH  HCHO  CO2  PM2.5
0    2017-02-01 00:01:49           16  53    33  400     13
1    2017-02-01 00:02:49           16  53    32  400     11
2    2017-02-01 00:03:50           16  53    33  400     16
3    2017-02-01 00:04:50           16  53    33  400      9
4    2017-02-01 00:05:53           16  53    33  400      8
5    2017-02-01 00:06:53           16  53    33  400     13
6    2017-02-01 00:07:53           16  53    32  400     11
7    2017-02-01 00:08:54           16  53    33  400     16
8    2017-02-01 00:09:54           16  53    33  400     10
9    2017-02-01 00:11:49           16  53    32  400     13
10   2017-02-01 00:12:50           16  53    33  400     10
11   2017-02-01 00:13:50           16  53    32  400     11
12   2017-02-01 00:14:50           16  53    33  400     13
13   2017-02-01 00:15:50           16  53    32  400     10
14   2017-02-01 00:16:50           16  53    33  400      8
15   2017-02-01 00:17:50           16  53    33  400      9
16   2017-02-01 00:18:50           16  53    32  400     10
17   2017-02-01 00:19:51           16  53    32  400     13
18   2017-02-01 00:21:50           16  53    33  400     13
19   2017-02-01 00:22:50           16  53    32  400     11
20   2017-02-01 00:23:50           16  53    32  400     12
21   2017-02-01 00:24:50           16  53    32  400     10
22   2017-02-01 00:25:50           16  53    33  400     10
23   2017-02-01 00:26:50           16  53    32  400     15
24   2017-02-01 00:27:50           16  53    33  400     11
25   2017-02-01 00:28:51           16  53    32  400     13
26   2017-02-01 00:29:51           16  53    33  400     10
27   2017-02-01 00:31:50           16  53    32  400     13
28   2017-02-01 00:32:50           16  53    33  400     14
29   2017-02-01 00:33:50           16  53    33  400     13
...                  ...          ...  ..   ...  ...    ...
8462 2017-02-28 23:27:55           15  52    30  442     18
8463 2017-02-28 23:28:55           15  52    30  441     18
8464 2017-02-28 23:29:55           15  52    30  440     17
8465 2017-02-28 23:31:54           15  52    32  439     22
8466 2017-02-28 23:32:54           15  52    30  439     18
8467 2017-02-28 23:33:54           15  52    32  440     17
8468 2017-02-28 23:34:55           15  52    30  440     23
8469 2017-02-28 23:35:55           15  52    30  439     23
8470 2017-02-28 23:36:55           15  52    30  440     19
8471 2017-02-28 23:37:55           15  52    30  440     21
8472 2017-02-28 23:38:55           15  52    30  440     20
8473 2017-02-28 23:39:55           15  52    30  440     24
8474 2017-02-28 23:41:54           15  52    30  440     18
8475 2017-02-28 23:42:54           15  52    30  439     21
8476 2017-02-28 23:43:55           15  52    30  439     23
8477 2017-02-28 23:44:55           15  52    30  439     22
8478 2017-02-28 23:45:58           15  52    30  438     22
8479 2017-02-28 23:46:58           15  52    30  438     23
8480 2017-02-28 23:47:58           15  52    30  439     19
8481 2017-02-28 23:48:58           15  52    30  439     20
8482 2017-02-28 23:49:59           15  52    30  439     18
8483 2017-02-28 23:51:54           15  52    30  439     24
8484 2017-02-28 23:52:54           15  52    30  439     22
8485 2017-02-28 23:53:55           15  52    30  438     20
8486 2017-02-28 23:54:55           15  52    30  437     21
8487 2017-02-28 23:55:55           15  52    30  437     18
8488 2017-02-28 23:56:55           15  52    30  437     24
8489 2017-02-28 23:57:55           15  52    30  437     23
8490 2017-02-28 23:58:55           15  52    32  437     22
8491 2017-02-28 23:59:56           15  52    30  437     23

[8492 rows x 6 columns]

In [141]:
ik=data['BR'].iloc[:,0:6]
TimeSeries=pd.to_datetime(data['BR'].iloc[:,0], format="%Y/%m/%d %H:%M:%S")
TimeSeries=pd.DatetimeIndex(TimeSeries)
month=TimeSeries.month
week=TimeSeries.weekday
hour=TimeSeries.hour

In [142]:
month=pd.Series(month)
week=pd.Series(week)
hour=pd.Series(hour)
timefactor={"Month":month,"Week":week, "Hour":hour }
timefactor=pd.DataFrame(timefactor)
ik=pd.merge(timefactor,ik,left_index=True,right_index=True)
ik

      Hour  Month  Week                Time  Temperature  RH  HCHO  CO2  PM2.5
0        0      2     2 2017-02-01 00:01:49           16  53    33  400     13
1        0      2     2 2017-02-01 00:02:49           16  53    32  400     11
2        0      2     2 2017-02-01 00:03:50           16  53    33  400     16
3        0      2     2 2017-02-01 00:04:50           16  53    33  400      9
4        0      2     2 2017-02-01 00:05:53           16  53    33  400      8
5        0      2     2 2017-02-01 00:06:53           16  53    33  400     13
6        0      2     2 2017-02-01 00:07:53           16  53    32  400     11
7        0      2     2 2017-02-01 00:08:54           16  53    33  400     16
8        0      2     2 2017-02-01 00:09:54           16  53    33  400     10
9        0      2     2 2017-02-01 00:11:49           16  53    32  400     13
10       0      2     2 2017-02-01 00:12:50           16  53    33  400     10
11       0      2     2 2017-02-01 00:13:50           16  53    32  400     11
12       0      2     2 2017-02-01 00:14:50           16  53    33  400     13
13       0      2     2 2017-02-01 00:15:50           16  53    32  400     10
14       0      2     2 2017-02-01 00:16:50           16  53    33  400      8
15       0      2     2 2017-02-01 00:17:50           16  53    33  400      9
16       0      2     2 2017-02-01 00:18:50           16  53    32  400     10
17       0      2     2 2017-02-01 00:19:51           16  53    32  400     13
18       0      2     2 2017-02-01 00:21:50           16  53    33  400     13
19       0      2     2 2017-02-01 00:22:50           16  53    32  400     11
20       0      2     2 2017-02-01 00:23:50           16  53    32  400     12
21       0      2     2 2017-02-01 00:24:50           16  53    32  400     10
22       0      2     2 2017-02-01 00:25:50           16  53    33  400     10
23       0      2     2 2017-02-01 00:26:50           16  53    32  400     15
24       0      2     2 2017-02-01 00:27:50           16  53    33  400     11
25       0      2     2 2017-02-01 00:28:51           16  53    32  400     13
26       0      2     2 2017-02-01 00:29:51           16  53    33  400     10
27       0      2     2 2017-02-01 00:31:50           16  53    32  400     13
28       0      2     2 2017-02-01 00:32:50           16  53    33  400     14
29       0      2     2 2017-02-01 00:33:50           16  53    33  400     13
...    ...    ...   ...                 ...          ...  ..   ...  ...    ...
8462    23      2     1 2017-02-28 23:27:55           15  52    30  442     18
8463    23      2     1 2017-02-28 23:28:55           15  52    30  441     18
8464    23      2     1 2017-02-28 23:29:55           15  52    30  440     17
8465    23      2     1 2017-02-28 23:31:54           15  52    32  439     22
8466    23      2     1 2017-02-28 23:32:54           15  52    30  439     18
8467    23      2     1 2017-02-28 23:33:54           15  52    32  440     17
8468    23      2     1 2017-02-28 23:34:55           15  52    30  440     23
8469    23      2     1 2017-02-28 23:35:55           15  52    30  439     23
8470    23      2     1 2017-02-28 23:36:55           15  52    30  440     19
8471    23      2     1 2017-02-28 23:37:55           15  52    30  440     21
8472    23      2     1 2017-02-28 23:38:55           15  52    30  440     20
8473    23      2     1 2017-02-28 23:39:55           15  52    30  440     24
8474    23      2     1 2017-02-28 23:41:54           15  52    30  440     18
8475    23      2     1 2017-02-28 23:42:54           15  52    30  439     21
8476    23      2     1 2017-02-28 23:43:55           15  52    30  439     23
8477    23      2     1 2017-02-28 23:44:55           15  52    30  439     22
8478    23      2     1 2017-02-28 23:45:58           15  52    30  438     22
8479    23      2     1 2017-02-28 23:46:58           15  52    30  438     23
8480    23      2     1 2017-02-28 23:47:58           15  52    30  439     19
8481    23      2     1 2017-02-28 23:48:58           15  52    30  439     20
8482    23      2     1 2017-02-28 23:49:59           15  52    30  439     18
8483    23      2     1 2017-02-28 23:51:54           15  52    30  439     24
8484    23      2     1 2017-02-28 23:52:54           15  52    30  439     22
8485    23      2     1 2017-02-28 23:53:55           15  52    30  438     20
8486    23      2     1 2017-02-28 23:54:55           15  52    30  437     21
8487    23      2     1 2017-02-28 23:55:55           15  52    30  437     18
8488    23      2     1 2017-02-28 23:56:55           15  52    30  437     24
8489    23      2     1 2017-02-28 23:57:55           15  52    30  437     23
8490    23      2     1 2017-02-28 23:58:55           15  52    32  437     22
8491    23      2     1 2017-02-28 23:59:56           15  52    30  437     23

[8492 rows x 9 columns]

In [143]:
week

0       2
1       2
2       2
3       2
4       2
5       2
6       2
7       2
8       2
9       2
10      2
11      2
12      2
13      2
14      2
15      2
16      2
17      2
18      2
19      2
20      2
21      2
22      2
23      2
24      2
25      2
26      2
27      2
28      2
29      2
       ..
8462    1
8463    1
8464    1
8465    1
8466    1
8467    1
8468    1
8469    1
8470    1
8471    1
8472    1
8473    1
8474    1
8475    1
8476    1
8477    1
8478    1
8479    1
8480    1
8481    1
8482    1
8483    1
8484    1
8485    1
8486    1
8487    1
8488    1
8489    1
8490    1
8491    1
Name: Time, Length: 8492, dtype: int64

In [144]:
wt=data['WT'].iloc[:,1:5]
wt = pd.DataFrame(wt.values, columns=wt.columns)
wt.head()

  Out_Temperature Out_RH Rain Wind_V
0               7     85    0    3-4
1               7     85    0    3-4
2               7     85    0    3-4
3               7     85    0    3-4
4               7     85    0    3-4

In [145]:
BRW=data['BRWin'].iloc[:,0:1]
BRW = pd.DataFrame(BRW.values, columns=BRW.columns)
BRW

     BRW
0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
..   ...
154    0
155    0
156    0
157    0
158    0
159    0
160    0
161    0
162    0
163    0
164    0
165    0
166    0
167    0
168    0
169    0
170    0
171    0
172    0
173    0
174    0
175    0
176    0
177    0
178    0
179    0
180    0
181    0
182    0
183    0

[184 rows x 1 columns]

In [146]:
PM=data['PM'].iloc[:,1:]
PM = pd.DataFrame(PM.values, columns=PM.columns)
PM.head()

,CO(mg/m3),NO2(ug/m3),SO2(ug/m3),O3(ug/m3),PM10(ug/m3),PM2.5(ug/m3),AQI
0,0.6,15.0,9.0,77.0,40.0,21.0,40.0
1,0.6,15.0,9.0,77.0,40.0,21.0,40.0
2,0.6,15.0,9.0,77.0,40.0,21.0,40.0
3,0.6,15.0,9.0,77.0,40.0,21.0,40.0
4,0.6,15.0,9.0,77.0,40.0,21.0,40.0

In [147]:
ikwt=pd.merge(ik,wt,left_index=True,right_index=True)

In [148]:
PMBRW=pd.merge(PM,BRW,left_index=True,right_index=True)
PMBRW

,CO(mg/m3),NO2(ug/m3),SO2(ug/m3),O3(ug/m3),PM10(ug/m3),PM2.5(ug/m3),AQI,BRW
0,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
1,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
2,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
3,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
5,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
6,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
7,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
8,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
9,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
10,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
11,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
12,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
13,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
14,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
15,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
16,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
17,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
18,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
19,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
20,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
21,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
22,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
23,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
24,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
25,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
26,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
27,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
28,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
29,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
...,...,...,...,...,...,...,...,...
154,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
155,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
156,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
157,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
158,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
159,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
160,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
161,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
162,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
163,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
164,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
165,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
166,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
167,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
168,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
169,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
170,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
171,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
172,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
173,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
174,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
175,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
176,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
177,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
178,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
179,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
180,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
181,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
182,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
183,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0

In [149]:
merged_data=pd.merge(ikwt,PMBRW,left_index=True,right_index=True,how="inner")
merged_data

,Hour,Month,Week,Time,Temperature,RH,HCHO,CO2,PM2.5,Out_Temperature,...,Rain,Wind_V,CO(mg/m3),NO2(ug/m3),SO2(ug/m3),O3(ug/m3),PM10(ug/m3),PM2.5(ug/m3),AQI,BRW
0,0,2,2,2017-02-01 00:01:49,16,53,33,400,13,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
1,0,2,2,2017-02-01 00:02:49,16,53,32,400,11,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
2,0,2,2,2017-02-01 00:03:50,16,53,33,400,16,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
3,0,2,2,2017-02-01 00:04:50,16,53,33,400,9,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
4,0,2,2,2017-02-01 00:05:53,16,53,33,400,8,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
5,0,2,2,2017-02-01 00:06:53,16,53,33,400,13,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
6,0,2,2,2017-02-01 00:07:53,16,53,32,400,11,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
7,0,2,2,2017-02-01 00:08:54,16,53,33,400,16,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
8,0,2,2,2017-02-01 00:09:54,16,53,33,400,10,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
9,0,2,2,2017-02-01 00:11:49,16,53,32,400,13,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
10,0,2,2,2017-02-01 00:12:50,16,53,33,400,10,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
11,0,2,2,2017-02-01 00:13:50,16,53,32,400,11,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
12,0,2,2,2017-02-01 00:14:50,16,53,33,400,13,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
13,0,2,2,2017-02-01 00:15:50,16,53,32,400,10,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
14,0,2,2,2017-02-01 00:16:50,16,53,33,400,8,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
15,0,2,2,2017-02-01 00:17:50,16,53,33,400,9,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
16,0,2,2,2017-02-01 00:18:50,16,53,32,400,10,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
17,0,2,2,2017-02-01 00:19:51,16,53,32,400,13,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
18,0,2,2,2017-02-01 00:21:50,16,53,33,400,13,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
19,0,2,2,2017-02-01 00:22:50,16,53,32,400,11,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
20,0,2,2,2017-02-01 00:23:50,16,53,32,400,12,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
21,0,2,2,2017-02-01 00:24:50,16,53,32,400,10,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
22,0,2,2,2017-02-01 00:25:50,16,53,33,400,10,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
23,0,2,2,2017-02-01 00:26:50,16,53,32,400,15,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
24,0,2,2,2017-02-01 00:27:50,16,53,33,400,11,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
25,0,2,2,2017-02-01 00:28:51,16,53,32,400,13,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
26,0,2,2,2017-02-01 00:29:51,16,53,33,400,10,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
27,0,2,2,2017-02-01 00:31:50,16,53,32,400,13,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
28,0,2,2,2017-02-01 00:32:50,16,53,33,400,14,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
29,0,2,2,2017-02-01 00:33:50,16,53,33,400,13,7,...,0,3-4,0.6,15.0,9.0,77.0,40.0,21.0,40.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2,2,2,2017-02-01 02:56:52,16,53,32,400,11,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
155,2,2,2,2017-02-01 02:57:53,16,53,33,400,12,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
156,2,2,2,2017-02-01 02:58:53,16,53,33,400,10,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
157,2,2,2,2017-02-01 02:59:53,16,53,32,400,9,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
158,3,2,2,2017-02-01 03:01:52,16,53,32,400,14,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
159,3,2,2,2017-02-01 03:02:52,16,53,33,400,13,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
160,3,2,2,2017-02-01 03:03:52,16,53,33,400,9,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
161,3,2,2,2017-02-01 03:04:52,16,53,32,400,10,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
162,3,2,2,2017-02-01 03:05:52,16,53,33,400,12,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
163,3,2,2,2017-02-01 03:06:53,16,53,32,400,10,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
164,3,2,2,2017-02-01 03:07:53,16,53,33,400,12,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
165,3,2,2,2017-02-01 03:08:53,16,53,32,400,11,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
166,3,2,2,2017-02-01 03:09:53,16,53,33,400,11,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
167,3,2,2,2017-02-01 03:12:03,16,53,33,400,14,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
168,3,2,2,2017-02-01 03:13:52,16,53,32,400,10,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
169,3,2,2,2017-02-01 03:14:52,16,53,33,400,7,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
170,3,2,2,2017-02-01 03:16:53,16,53,32,400,12,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
171,3,2,2,2017-02-01 03:17:53,16,53,32,400,11,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
172,3,2,2,2017-02-01 03:18:54,16,53,33,400,9,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
173,3,2,2,2017-02-01 03:19:54,16,53,32,400,13,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
174,3,2,2,2017-02-01 03:21:52,16,53,32,400,12,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
175,3,2,2,2017-02-01 03:22:52,16,53,32,400,13,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
176,3,2,2,2017-02-01 03:23:52,16,53,32,400,12,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
177,3,2,2,2017-02-01 03:24:53,16,53,32,400,14,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
178,3,2,2,2017-02-01 03:25:53,16,53,33,400,9,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
179,3,2,2,2017-02-01 03:26:53,16,53,32,400,13,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
180,3,2,2,2017-02-01 03:27:53,16,53,32,400,9,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
181,3,2,2,2017-02-01 03:28:53,16,53,32,400,14,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
182,3,2,2,2017-02-01 03:29:53,16,53,32,400,9,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0
183,3,2,2,2017-02-01 03:31:52,16,53,32,400,12,7,...,0,3-4,0.7,31.0,9.0,50.0,48.0,22.0,48.0,0